version: '3.5'

services:
  web:
    env_file:
      - .env
    build:
      dockerfile: docker/web/Dockerfile
      context: ./
    ports:
      - 8999:80
    environment:
      DB_HOST: db
      DB_NAME: form
      DB_USERNAME: form
      DB_PASSWORD: form
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./sql:/app/sql
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: form
      MYSQL_USER: form
      MYSQL_PASSWORD: form
  ngrok:
    image: gtriggiano/ngrok-tunnel
    ports:
      - 4040:4040
    environment:
      TARGET_HOST: web
      TARGET_PORT: 80
      NGROK_TOKEN: "${NGROK_AUTHTOKEN}"
    depends_on:
      - web
